#ifndef __psp_msg__
#define __psp_msg__

enum {
	MSG_EN,
	MSG_JA,

	MSG_TOTAL_LANG
};

enum {
	//error
	ERR_OUT_OF_MEM,
	ERR_READ_MEMSTICK,

	ERR_INIT_SNES,
	ERR_LOADING_ROM,
	ERR_INIT_GFX,

	ERR_CANNOT_ALLOC_MEM,

	ERR_USB_STARTING_USBBUS,
	ERR_USB_STARTING_USBMASS,
	ERR_USB_SETTING_CAPACITY,

	ERR_INIT_OSK,
	ERR_ADD_CODE,

	//confirm
	ASK_EXIT,
	ASK_DELETE,
	ASK_SAVEDIR,

	//info
	INFO_USB_ON,
	INFO_USB_OFF,
	INFO_DELETING,
	INFO_EXITING,

	//filer
	FILER_STATUS_CANEXIT1,
	FILER_STATUS_NOEXIT1,
	FILER_STATUS_CANEXIT2,
	FILER_STATUS_NOEXIT2,

	FILER_STATUS_PARDIR,

	FILER_TITLE,

	FILER_HELP_WINDOW1,
	FILER_HELP_WINDOW2,
	FILER_HELP_WINDOW3,
	FILER_HELP_WINDOW4,
	FILER_HELP_WINDOW5,

	FILE_IPS_APPLYING,
	FILE_IPS_PATCHSUCCESS,


	// GAME
	MENU_ICONS_GAME,
	MENU_ICONS_GAME_RESET,
	MENU_ICONS_GAME_NEW,
	MENU_ICONS_GAME_DEFAULTSETTINGS,
	MENU_ICONS_GAME_DEFAULTSETTINGS_HELP,
	MENU_ICONS_GAME_EXIT,

	MENU_GAME_SAVINGDEFAULTSETTINGS,
	MENU_GAME_CONFIRMRESET,
	// LOAD/SAVE
	MENU_ICONS_LOADSAVE,
	MENU_ICONS_LOADSAVE_LOADSTATE,
	MENU_ICONS_LOADSAVE_LOADSTATE_HELP,
	MENU_ICONS_LOADSAVE_SAVESTATE,
	MENU_ICONS_LOADSAVE_SAVESTATE_HELP,
	MENU_ICONS_LOADSAVE_DELETESTATE,
	MENU_ICONS_LOADSAVE_DELETESTATE_HELP,
	MENU_ICONS_LOADSAVE_IMPORTSTATE,
	MENU_ICONS_LOADSAVE_IMPORTSTATE_HELP,
	MENU_ICONS_LOADSAVE_AUTOSAVETIMER,
	MENU_ICONS_LOADSAVE_AUTOSAVETIMER_HELP,
	MENU_ICONS_LOADSAVE_AUTOSRAM,
	MENU_ICONS_LOADSAVE_AUTOSRAM_HELP,

	MENU_ICONS_LOADSAVE_EXPORTS9XSTATE,
	MENU_ICONS_LOADSAVE_EXPORTS9XSTATE_HELP,

	MENU_STATE_CHOOSEDEL,
	MENU_STATE_CHOOSELOAD,
	MENU_STATE_CHOOSESAVE,
	MENU_STATE_FREESLOT,
	MENU_STATE_SCANNING,

	MENU_STATE_CONFIRMLOAD,
	MENU_STATE_CONFIRMDELETE,
	MENU_STATE_CONFIRMSAVE,
	MENU_STATE_ISLOADING,
	MENU_STATE_ISSAVING,
	MENU_STATE_ISDELETING,
	MENU_STATE_ISIMPORTING,
	MENU_STATE_ISEXPORTINGS9X,
	MENU_STATE_NOSTATE,

	MENU_STATE_AUTOSAVETIMER,
	MENU_STATE_AUTOSAVETIMER_OFF,

	MENU_STATE_WARNING_LOWBAT,

	// CONTROLS
	MENU_ICONS_CONTROLS,
	MENU_ICONS_CONTROLS_REDEFINE,
	MENU_ICONS_CONTROLS_REDEFINE_HELP,
	MENU_ICONS_CONTROLS_INPUT,
	MENU_ICONS_CONTROLS_INPUT_HELP,

	MENU_CONTROLS_INPUT,
	MENU_CONTROLS_INPUT_PRESS,
	MENU_CONTROLS_INPUT_NOFORMENU,
	MENU_CONTROLS_INPUT_DEFAULT,

	MENU_STATUS_CONTROLS_INPUT,
	MENU_STATUS_CONTROLS_INPUT_0,
	MENU_STATUS_CONTROLS_INPUT_HELP_0,
	MENU_STATUS_CONTROLS_INPUT_HELP_1,
	MENU_STATUS_CONTROLS_INPUT_HELP_2,
	MENU_STATUS_CONTROLS_INPUT_HELP_3,

	MENU_TITLE_CONTROLS_INPUT,

	// VIDEO OPTIONS
	MENU_ICONS_VIDEO,
	MENU_ICONS_VIDEO_MODE,
	MENU_ICONS_VIDEO_MODE_HELP,
	MENU_ICONS_VIDEO_ENGINE,
	MENU_ICONS_VIDEO_ENGINE_HELP,
	MENU_ICONS_VIDEO_SLIMITONOFF,
	MENU_ICONS_VIDEO_SLIMITONOFF_HELP,
	MENU_ICONS_VIDEO_SLIMITVALUE,
	MENU_ICONS_VIDEO_SLIMITVALUE_HELP,
	MENU_ICONS_VIDEO_FSKIP,
	MENU_ICONS_VIDEO_FSKIP_HELP,
	MENU_ICONS_VIDEO_VSYNC,
	MENU_ICONS_VIDEO_VSYNC_HELP,
	MENU_ICONS_VIDEO_SMOOTHING,
	MENU_ICONS_VIDEO_SMOOTHING_HELP,
	MENU_ICONS_VIDEO_PALASNTSC,
	MENU_ICONS_VIDEO_PALASNTSC_HELP,
	MENU_ICONS_VIDEO_GAMMA,
	MENU_ICONS_VIDEO_GAMMA_HELP,
	MENU_ICONS_VIDEO_SCRCALIB,
	MENU_ICONS_VIDEO_SCRCALIB_HELP,
	MENU_ICONS_VIDEO_SHOWFPS,
	MENU_ICONS_VIDEO_SHOWFPS_HELP,

	MENU_VIDEO_MODE_1_1,
	MENU_VIDEO_MODE_ZOOM_FIT,
	MENU_VIDEO_MODE_ZOOM_4_3RD,
	MENU_VIDEO_MODE_ZOOM_WIDE,
	MENU_VIDEO_MODE_FULLSCREEN,
	MENU_VIDEO_MODE_FULLSCREEN_CLIPPED,
	MENU_VIDEO_ENGINE_APPROX,
	MENU_VIDEO_ENGINE_ACCUR,
	MENU_VIDEO_ENGINE_ACCEL,
	MENU_VIDEO_ENGINE_ACCEL_ACCUR,
	MENU_VIDEO_ENGINE_ACCEL_APPROX,
	MENU_VIDEO_SLIMITVALUE_AUTO,
	MENU_VIDEO_FSKIP_MODE_AUTO,
	MENU_VIDEO_FSKIP_CHANGEAUTO_AUTO,
	MENU_VIDEO_FSKIP_CHANGEAUTO_FIXED,

	MENU_STATUS_VIDEO_SCRCALIB,

	// SOUND OPTIONS
	MENU_ICONS_SOUND,
	MENU_ICONS_SOUND_MODE,
	MENU_ICONS_SOUND_MODE_HELP,
	MENU_ICONS_SOUND_FREQ,
	MENU_ICONS_SOUND_FREQ_HELP,
	MENU_ICONS_SOUND_APURATIO,
	MENU_ICONS_SOUND_APURATIO_HELP,

	MENU_SOUND_MODE_NOTEMUL,
	MENU_SOUND_MODE_EMULOFF,
	MENU_SOUND_MODE_EMULON,


	// MISC OPTIONS
	MENU_ICONS_MISC,
	MENU_ICONS_MISC_FILEVIEWER,
	MENU_ICONS_MISC_FILEVIEWER_HELP,
	MENU_ICONS_MISC_PSPCLOCK,
	MENU_ICONS_MISC_PSPCLOCK_HELP,
	MENU_ICONS_MISC_HACKDEBUG,
	MENU_ICONS_MISC_HACKDEBUG_HELP,
	MENU_ICONS_MISC_SNAPSHOT,
	MENU_ICONS_MISC_SNAPSHOT_HELP,
	MENU_ICONS_MISC_SWAPBG,
	MENU_ICONS_MISC_SWAPBG_HELP,
	MENU_ICONS_MISC_BGMUSIC,
	MENU_ICONS_MISC_BGMUSIC_HELP,
	MENU_ICONS_MISC_BGFX,
	MENU_ICONS_MISC_BGFX_HELP,
	MENU_ICONS_MISC_PADBEEP,
	MENU_ICONS_MISC_PADBEEP_HELP,
	MENU_ICONS_MISC_AUTOSTART,
	MENU_ICONS_MISC_AUTOSTART_HELP,
	MENU_ICONS_MISC_OSK,
	MENU_ICONS_MISC_OSK_HELP,

	MENU_MUSIC_SWAPBG_NODATA,
	MENU_MISC_SWAPBG_RAND,

	MENU_MISC_SAVINGJPEG,

	MENU_MISC_BGMUSIC_RAND,
	MENU_MISC_BGMUSIC_ORDER,

	MENU_MISC_BGMUSIC_GAMETITLE,
	MENU_MISC_BGMUSIC_TITLE,
	MENU_MISC_BGMUSIC_AUTHOR,
	MENU_MISC_BGMUSIC_UNKNOWN,

	MENU_MISC_OSK_DANZEFF,
	MENU_MISC_OSK_OFFICIAL,

	MENU_STATUS_MISC_HACKDEBUG,
	MENU_STATUS_MISC_HACKDEBUG_FUNC,
	MENU_STATUS_MISC_HACKDEBUG_0,
	MENU_STATUS_MISC_HACKDEBUG_HELP_0,
	MENU_STATUS_MISC_HACKDEBUG_HELP_1,
	MENU_STATUS_MISC_HACKDEBUG_HELP_2,
	MENU_STATUS_MISC_HACKDEBUG_HELP_3,

	MENU_TITLE_MISC_HACKDEBUG,

	// CHEATS
	MENU_ICONS_CHEATS,
	MENU_ICONS_CHEATS_ADDRAW,
	MENU_ICONS_CHEATS_ADDRAW_HELP,
	MENU_ICONS_CHEATS_ADDGG,
	MENU_ICONS_CHEATS_ADDGG_HELP,
	MENU_ICONS_CHEATS_ADDPAR,
	MENU_ICONS_CHEATS_ADDPAR_HELP,
	MENU_ICONS_CHEATS_ADDGF,
	MENU_ICONS_CHEATS_ADDGF_HELP,
	MENU_ICONS_CHEATS_DISABLE,
	MENU_ICONS_CHEATS_DISABLE_HELP,
	MENU_ICONS_CHEATS_DISABLEALL,
	MENU_ICONS_CHEATS_DISABLEALL_HELP,
	MENU_ICONS_CHEATS_ENABLE,
	MENU_ICONS_CHEATS_ENABLE_HELP,
	MENU_ICONS_CHEATS_ENABLEALL,
	MENU_ICONS_CHEATS_ENABLEALL_HELP,
	MENU_ICONS_CHEATS_REMOVE,
	MENU_ICONS_CHEATS_REMOVE_HELP,
	MENU_ICONS_CHEATS_REMOVEALL,
	MENU_ICONS_CHEATS_REMOVEALL_HELP,

	MENU_CHEATS_ENTERGF,
	MENU_CHEATS_ENTERPAR,
	MENU_CHEATS_ENTERGG,
	MENU_CHEATS_ENTERRAW,
	MENU_CHEATS_ENTERNAME,
	MENU_CHEATS_CONFIRMREMALL,
	MENU_CHEATS_PREVPAGE,
	MENU_CHEATS_NEXTPAGE,

	// ABOUT
	MENU_ICONS_ABOUT,
	MENU_ICONS_ABOUT_CREDITS,
	MENU_ICONS_ABOUT_VERSION,

	MENU_ABOUT_VERSION_TIMESTAMP,
	MENU_ABOUT_VERSION_GCCVER,

	// MENU GENERIC (status bar, ...)
	MENU_STATUS_GENERIC_MSG1,
	MENU_STATUS_GENERIC_NEEDRELOAD,
	MENU_STATUS_GENERIC_NEEDRESET,
	MENU_STATUS_GENERIC_FREERAM,
	MENU_STATUS_GENERIC_CHANGEMUSIC,

	MENU_TITLE_GENERIC_BAT,
	MENU_TITLE_GENERIC_BAT_TIME,
	MENU_TITLE_GENERIC_BAT_PLG,
	MENU_TITLE_GENERIC_BAT_CHRG,
	MENU_TITLE_GENERIC_BAT_LOW,

	MENU_CHANGE_VALUE,
	MENU_CHANGE_VALUE_WITH_FAST,
	MENU_CANCEL_VALIDATE,
	MENU_DEFAULT_VALUE,
	MENU_YES,
	MENU_NO,
	MENU_NOT_IMPLEMENTED,

	//Others
	// Adhoc
	ADHOC_CONNECTING,
	ADHOC_SELECTORRETURN,
	ADHOC_WAITING,
	ADHOC_REQUESTED,
	ADHOC_CONNECTED,
	ADHOC_STATE,
	ADHOC_UNKNOWNCOMMAND,
	ADHOC_SYNCLOST_SERVER,
	ADHOC_SYNCLOST_CLIENT,
	ADHOC_CLOSING,
	ADHOC_DRIVERLOAD_ERR,
	ADHOC_INIT_ERR,
	ADHOC_LOST_CONNECTION,
	ADHOC_CORRUPTED_PKT,
	ADHOC_STATE_SIZE,
	ADHOC_FILE_ERR_RECEIVING,
	ADHOC_FILE_ERR_SENDING,
	ADHOC_STILL,
	ADHOC_WAITING_OTHER,
	ADHOC_NETWORKERR_1,
	ADHOC_CANNOTFIND,
	ADHOC_FLUSHING,
	// LOAD/SAVE
	LOADSAVE_AUTOSAVETIMER,
	LOADSAVE_EXPORTS9XSTATE,
	// VIDEO
	VIDEO_ENGINE_APPROX,
	VIDEO_ENGINE_ACCUR,
	VIDEO_ENGINE_ACCEL,
	VIDEO_ENGINE_ACCEL_ACCUR,
	VIDEO_ENGINE_ACCEL_APPROX,
	VIDEO_FSKIP_AUTO,
	VIDEO_FSKIP_MANUAL,
	// Scroll Message
	SCROLL_TITLE,
	SCROLL_STATUS_0,
	SCROLL_STATUS_1,
	SCROLL_HELP,
	SCROLL_SEARCHING,
	SCROLL_STRNOTFOUND,
	SCROLL_DISCLAIMER,
	SCROLL_OSK_DESC,
	//Settings
	SETTINGS_NOTCOMPLETE,
	SETTINGS_NOTFOUND,
	SETTINGS_FORCING_DEFAULT,
	SETTINGS_IGNORED,
	SETTINGS_FOUND,
	SETTINGS_DIFF,
	// Others
	APU_DEBUGGING,
	BGMUSIC_PLAYING,
	FOUND_SRAM,
	CANCEL,
	INPUTBOX_OK,
	BAT_ISLOW,
	CONV_DONE,
	ROM_LIED,
	LOADING_ROM,
	TYPE,
	MODE,
	COMPANY,
#ifdef _BSX_151_
	SRAM_NOTFOUND,
	SRAM_BSX_NOTFOUND,
#endif
	CORRUPT,
	ROM_ONLY,
	EXTENDING,
	EXTENDING_TARGET,
	INIT_OSK,

	MSG_TOTAL_ENTRIES
};

extern const char **s9xTYL_msg;

void psp_msg_init();

#endif
